AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Week 3 - Serverless API with Lambda, API Gateway, and DynamoDB

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.12
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"

Resources:
  # DynamoDB Table
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-items'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Function
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.lambda_handler
      Description: Handles API requests for items
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        CreateItem:
          Type: HttpApi
          Properties:
            Path: /items
            Method: POST
            ApiId: !Ref MyHttpApi
        GetItem:
          Type: HttpApi
          Properties:
            Path: /items/{id}
            Method: GET
            ApiId: !Ref MyHttpApi

  # HTTP API Gateway
  MyHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "Content-Type"
          - "X-Amz-Date"
          - "Authorization"
          - "X-Api-Key"
          - "X-Amz-Security-Token"
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        MaxAge: 600

Outputs:
  ApiUrl:
    Description: URL of the HTTP API
    Value: !Sub 'https://${MyHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
  
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref ApiFunction
  
  TableName:
    Description: DynamoDB Table Name
    Value: !Ref ItemsTable

